# Travis CI configuration
# @see https://mirocupak.com/continuous-integration-for-latex/
# @see https://tex.stackexchange.com/a/398831/174531
language: generic
sudo: required
dist: trusty
# DO NOT CACHE DEBIAN PACKAGES

branches:
  except:
    - deploy

before_install:
  - sudo apt -qq update > /dev/null
  - sudo apt install -y --no-install-recommends texlive-full > /dev/null

script:
  - chmod u+x scripts/compile.sh && ./scripts/compile.sh
  # publish files (such as *.pdf and *.log) onto deploy branch on Github
  - chmod u+x scripts/deploy.sh && ./scripts/deploy.sh
