# Travis CI configuration
# @see https://mirocupak.com/continuous-integration-for-latex/
# @see https://tex.stackexchange.com/a/398831/174531
language: generic
sudo: required
dist: trusty
# DO NOT CACHE DEBIAN PACKAGES

branches:
  except:
    - deploy

before_install:
  - sudo apt -qq update > /dev/null
  - sudo apt install -y --no-install-recommends texlive-full > /dev/null

script:
  # `-interaction=nonstopmode` sets the interaction mode to nonstop,
  #     which makes TeX run without requiring feedback from the user,
  #     through the errors.
  # `-halt-on-error` ensures TeX exits with an error code
  #     when an error is encountered during processing,
  #     thus failing the build in Travis CI.
  - pdflatex -interactive=nonstopmode -halt-on-error *.tex > /dev/null

after_success:
  # publish files (such as *.pdf and *.log) onto deploy branch on Github
  - chmod u+x deploy.sh && ./deploy.sh *.pdf *.log

after_failure:
  - chmod u+x deploy.sh && ./deploy.sh *.log
