# Travis CI configuration
# @see https://mirocupak.com/continuous-integration-for-latex/
# @see https://tex.stackexchange.com/a/398831/174531
language: generic
sudo: required
dist: trusty
# DO NOT CACHE DEBIAN PACKAGES

branches:
  except:
    - deploy

before_install:
  - sudo apt -qq update > /dev/null
  - sudo apt install -y --no-install-recommends texlive-full > /dev/null

script:
  - make compile
  - make deploy
